import Link from 'next/link';
import { PageHero } from '@/components/shared/page-hero';
import { DataNote } from './shared';
import { RankingTable } from './ranking-table';
import { readPortal } from '@/lib/portal/data';
import type { TournamentData } from '@/lib/portal/contracts';
const dailyMetrics=[['MESO_EARNED','Mesos earned'],['MESO_SPENT','Mesos spent'],['NX_EARNED','NX earned'],['NX_SPENT','NX spent'],['CUBES_FOUND','Cubes found'],['MIRACLE_CUBES_SPENT','Normal Miracle Cubes used'],['PREMIUM_CUBES_SPENT','Premium Miracle Cubes used'],['SUPER_CUBES_SPENT','Super Miracle Cubes used'],['MOBS_KILLED','Mobs defeated'],['UNIQUE_BOSSES_SLAIN','Unique bosses slain'],['DEATHS_ACHIEVED','Deaths achieved']];
const weeklyMetrics=[['combat.mobs_killed','Mobs defeated'],['combat.bosses_killed','Bosses defeated'],['combat.unique_bosses_killed','Unique bosses'],['progress.exp_earned','EXP earned'],['items.cubes_spent','Cubes used']];
export async function CompetitionPage({period,params}:{period:'daily'|'weekly';params:Record<string,string|string[]|undefined>}) {
 const metrics=period==='daily'?dailyMetrics:weeklyMetrics;
 const metric=typeof params.metric==='string'&&metrics.some(m=>m[0]===params.metric)?params.metric:period==='daily'?'MOBS_KILLED':metrics[0][0];
 const dateKey=period==='daily'?'date':'weekStart';
 const raw=params[dateKey]; let selectedDate:string|undefined;
 if(typeof raw==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(raw)&&Number.isFinite(Date.parse(raw+'T00:00:00Z'))&&new Date(raw+'T00:00:00Z').toISOString().slice(0,10)===raw)selectedDate=raw;
 const response=await readPortal<TournamentData>('/api/rankings/'+period,{metric,[dateKey]:selectedDate,limit:100});
 const data=response.data;
 return <main><PageHero eyebrow={period==='daily'?'A FRESH CHALLENGE':'SEVEN DAYS. ONE GREAT JOURNEY.'} title={period==='daily'?'Make today count.':'A week to remember.'} description={period==='daily'?'The daily competition is being prepared. Follow a metric, choose a day, and discover the top 100 when the event opens.':'A new way to follow the week’s adventurers. Weekly standings are planned for a future beta update.'}/><section className="shell portal-section"><nav className="portal-tabs" aria-label="Ranking period"><Link href="/rankings">Overall</Link><Link href="/rankings/daily" aria-current={period==='daily'?'page':undefined}>Daily competition</Link><Link href="/rankings/weekly" aria-current={period==='weekly'?'page':undefined}>Weekly rankings</Link></nav><form className="search-form" action={'/rankings/'+period}><label className="field">Competition metric<select name="metric" defaultValue={metric}>{metrics.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field">{period==='daily'?'Historical date':'Week starting'}<input name={dateKey} type="date" defaultValue={selectedDate}/></label><button className="button button-gold" type="submit">View standings</button></form><DataNote response={response}/><p className="data-note">{period === 'daily' ? 'These are the 11 planned tournament categories. Economy coverage remains partial; scoring sources, boss eligibility and anti-farming rules must be verified before standings open.' : 'These weekly metrics are a proposal. Weekly aggregation, eligibility and finalization still require server implementation.'}</p><div className="portal-panel">{data&&<div className="stat-grid"><div className="stat-tile"><span>Period</span><strong>{data.date??data.weekStart}</strong></div><div className="stat-tile"><span>Result</span><strong>{data.finalized?'Finalized':'Provisional'}</strong></div><div className="stat-tile"><span>Winner</span><strong>{data.finalized?data.winner??'No winner':'Not finalized'}</strong></div><div className="stat-tile"><span>Timezone</span><strong>{data.zone}</strong></div></div>}<RankingTable entries={data?.entries??[]} competition/></div><div className="portal-two-grid"><article className="portal-panel"><h2>A fair place to compete.</h2><p>Competition rules will define eligible characters, scoring and tie-breaks before launch. Only finalized standings can name a winner.</p></article><article className="portal-panel"><h2>{period==='daily'?'The day’s top 100.':'Follow the whole week.'}</h2><p>{period==='daily'?'Historical dates and the top 100 are prepared here. The tournament and reward systems still need server validation.':'Weekly scoring is still in development. This page will open once the server supports a verified weekly competition.'}</p></article></div></section></main>;
}
