import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, ArrowUpRight, Download, Swords, Flame, Gem, Trophy, BookOpen, Users, Sparkles } from 'lucide-react';
import { readPortal } from '@/lib/portal/data';
import type { StatusData, RankingsData, TournamentData } from '@/lib/portal/contracts';
import { SectionHeading } from '@/components/portal/shared';
import { HomeLeaders } from '@/components/portal/home-leaders';
export const dynamic='force-dynamic';
export default async function Home() {
 const [status,overall,daily,weekly] = await Promise.all([readPortal<StatusData>('/api/status'),readPortal<RankingsData>('/api/rankings'),readPortal<TournamentData>('/api/rankings/daily'),readPortal<TournamentData>('/api/rankings/weekly')]);
 const state=status.data?.online===true?'Online':status.data?.online===false?'Offline':'Status unavailable';
 return <main className="beta-home">
 <section className="portal-hero" aria-labelledby="home-title"><Image className="portal-hero-art" src="/art/trixter-world.webp" fill priority sizes="100vw" alt="An original fantasy village among autumn trees, floating islands and luminous waterfalls"/><div className="portal-hero-shade"/><div className="shell portal-hero-content"><div className="hero-kicker"><span/> GMS v111.1 <i/> THE BETA CHAPTER</div><h1 id="home-title">A familiar world.<br/><em>A new adventure.</em></h1><p>Return to the world you remember.<br/>Discover the one we’re building together.</p><div className="hero-buttons"><Link href="/download" className="button button-gold"><Download size={18}/> Play TrixterMS <ArrowRight size={18}/></Link><Link href="/features" className="button button-glass">Explore the world <ArrowUpRight size={17}/></Link></div><div className="hero-footnote"><span>Classic roots</span><i/><span>Remastered possibilities</span><i/><span>A world of your own</span></div></div><span className="hero-art-caption">THE JOURNEY BEGINS AGAIN</span></section>
 <section className="world-strip" aria-label="Server information"><div className="shell world-strip-inner"><div><span>World status</span><strong><i className={'world-dot '+(status.data?.online?'online':'')}/>{state}</strong></div><div><span>Adventurers online</span><strong>{status.data?.playersOnline?.toLocaleString()??'—'} <small>players</small></strong></div><div><span>Our foundation</span><strong>{status.data?.version??'GMS v111.1'}</strong></div><div><span>EXP / Mesos / Drop</span><strong>{status.data?['exp','meso','drop'].map(k=>{const value=status.data?.rates[k as 'exp'|'meso'|'drop'];return value===null||value===undefined?'—':value+'×'}).join(' / '):'Awaiting world feed'}</strong></div><Link href="/status" aria-label="View full server status"><ArrowUpRight size={24}/></Link></div>{status.status==='fixture'&&<p className="shell data-note">Local development fixture · not live server status</p>}</section>
 <div className="shell portal-main">
 <section className="home-journal"><div className="journal-main"><SectionHeading eyebrow="FROM THE TRIXTER JOURNAL" title="The next chapter, together." href="/news" label="All news"/><Link className="journal-feature" href="/news#beta-portal"><div className="journal-feature-art"><Sparkles size={50} strokeWidth={1}/><span>THE BETA CHAPTER</span></div><div><span className="pill">DEVELOPMENT UPDATE</span><h3>A home for your next adventure.</h3><p>A new portal for beta downloads, character journeys, and the stories still to come.</p><span className="inline-link">Read the journal <ArrowUpRight size={16}/></span></div></Link><div className="journal-mini-grid"><Link href="/classes"><span>CLASS SPOTLIGHT</span><h3>New life for the original jobs.</h3><small>Inside Explorer Remaster <ArrowUpRight size={14}/></small></Link><Link href="/achievements"><span>THE LONG GAME</span><h3>Make every milestone matter.</h3><small>Explore the achievement catalog <ArrowUpRight size={14}/></small></Link></div></div><aside><SectionHeading eyebrow="THE HALL OF ADVENTURERS" title="Leave your mark."/><HomeLeaders overall={overall} daily={daily} weekly={weekly}/></aside></section>
 <section className="home-features"><SectionHeading eyebrow="FAMILIAR ROOTS. NEW POSSIBILITIES." title="More reasons to return." href="/features" label="Discover TrixterMS"/><div className="feature-cards"><Link href="/classes" className="feature-card explorer-card"><Swords className="feature-art" size={108} strokeWidth={.7}/><span className="pill">CLASS REMASTERS</span><h3>The explorers.<br/>Reimagined.</h3><p>Your favorite jobs, with a new chapter to master.</p><span className="inline-link">Explorer Remaster <ArrowUpRight size={16}/></span></Link><Link href="/classes#demon-avenger" className="feature-card avenger-card"><Flame className="feature-art" size={115} strokeWidth={.7}/><span className="pill">IN DEVELOPMENT</span><h3>Power with<br/>a different pulse.</h3><p>Meet Demon Avenger, our next class adventure.</p><span className="inline-link">Meet Demon Avenger <ArrowUpRight size={16}/></span></Link><Link href="/features" className="feature-card systems-card"><Gem className="feature-art" size={104} strokeWidth={.7}/><span className="pill">CUSTOM SYSTEMS</span><h3>Progress that<br/>stays with you.</h3><p>Cards, cubing, and milestones for the long journey.</p><span className="inline-link">Discover the systems <ArrowUpRight size={16}/></span></Link></div></section>
 <section className="home-milestones"><div><span className="eyebrow">SMALL STEPS. GREAT STORIES.</span><h2>Every adventure<br/>has its milestones.</h2><p>Explore the staged beta catalog: 40 achievements across eight paths. Character progress will arrive with the public world feed.</p><Link href="/achievements" className="inline-link">Explore achievements <ArrowRight size={17}/></Link></div><div className="milestone-cards"><Link href="/achievements"><Trophy size={28}/><strong>First Steps</strong><span>Reach level 10</span><small>CATALOG PREVIEW · 10 AP</small></Link><Link href="/achievements"><BookOpen size={28}/><strong>Find your path</strong><span>Combat, exploration & more</span><small>8 ACHIEVEMENT CATEGORIES</small></Link><Link href="/database"><Gem size={28}/><strong>Know your world</strong><span>Items, monsters & equipment</span><small>EXPLORE THE DATABASE</small></Link></div></section>
 <section className="recent-unlocks portal-panel" aria-labelledby="recent-unlocks-title"><span className="eyebrow">MOMENTS WORTH REMEMBERING</span><h2 id="recent-unlocks-title">Latest achievement unlocks.</h2><p>Fresh milestones from across the world will appear here when the public achievement feed opens.</p><span className="pill">RECENT UNLOCKS UNAVAILABLE</span></section><section className="community-banner"><div className="community-icon"><Users size={58} strokeWidth={1}/></div><div><span className="eyebrow">BETTER WITH A PARTY</span><h2>Your people. Your next story.</h2><p>Find a party, follow development, and help shape the beta.</p></div><Link href="/discord" className="button button-gold">Join the community <ArrowUpRight size={18}/></Link></section>
 <section className="home-start"><span className="eyebrow">READY FOR A NEW CHAPTER?</span><h2>See you in TrixterMS.</h2><p>Create your account, get the verified client, and sign in through the native game login flow.</p><Link href="/download" className="button button-gold"><Download size={17}/> Download & get started</Link></section>
 </div></main>;
}
